config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  resources :representatives
  resources :candidates, controller: 'representatives', type: 'Candidate'
  resources :ambassadors, controller: 'representatives', type: 'Ambassador'

  resources :proposals do
    resources :comments
    resources :promissories do
      collection { get :preview }
    end
    member do
      put "like", to: "proposals#upvote"
      put "dislike", to: "proposals#downvote"
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'

  def index
    @statistics = Stats.find_by(name: '2014 Statistics')
  end
end

app/views/welcome/index.html.haml
%body
  .navbar-wrapper
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          = link_to '#', data: { target: '.nav-collapse', toggle: 'collapse' } do
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %h1.brand
            = link_to 'DonaMaria', '#top'
          %nav.pull-right.nav-collapse.collapse
            %ul#menu-main.nav
              - ['Representação', 'Financiamento', 'Participe', 'Quem Somos', 'Hackathon'].each do |nav_item|
                %li
                  = link_to nav_item, "##{nav_item.parameterize}"
              %li.login-btn-wrapper
                = link_to 'Entrar', new_user_session_path, class: 'btn legend login', data: { no_turbolink: true }
  #top
  #headerwrap
    %header.clearfix
      %h1
        %span= t('donamaria.title')
        = t('donamaria.headline')

      %ul.icon
        %li= image_tag 'feminismopunho.png', size: "40"
        %li= image_tag 'justica-gender.png', size: "60"
        %li= image_tag 'hackathon.png', size: "50"
        %li= image_tag 'outubro-rosa.png', size: "45"

  .scrollblock
    %section#feature
      .container
        .row
          .span12
            %article
              %p= t '.introduction_html',
                transparency_law: link_to('Lei de Acesso à Informação', 'http://www.acessoainformacao.gov.br/assuntos/conheca-seu-direito/a-lei-de-acesso-a-informacao', target: '_blank'),
                open_data: link_to('Dados Abertos', 'http://dados.gov.br/dados-abertos/', target: '_blank'),
                mcn: link_to('Meu Congresso Nacional', 'http://meucongressonacional.com/api', target: '_blank')
  %hr

  %section#representacao.single-page.scrollblock
    .container
      %article.post
        %h1.folio-headline= t('.representation.title')
        %p= t('.representation.body')
      #representacao-row.row
        .span5
          %article.post
            %hgroup
              %h2= t('.representation.candidates.title')
            .entry-content
              %p= t('.representation.candidates.body')
            #candidates-statistics{ data: { men: @statistics.men_candidates, women: @statistics.women_candidates } }
            #piechart_candidatos
        .span5
          %article.post
            %hgroup
              %h2= t('.representation.elected_candidates.title')
            .entry-content
              %p= t('.representation.elected_candidates.body')
            #elected-candidates-statistics{ data: { men: @statistics.men_elected, women: @statistics.women_elected } }
            #piechart_eleitos
  %hr

  .scrollblock
    %section#feature
      .container
        .row
          .span12
            %article
              %p= t('.development')
  %hr

  %section#financiamento.single-page.scrollblock
    .container
      %article.post
        %h1.folio-headline= t('.campaign_funding.title')
        %p= t('.campaign_funding.body')
      #financiamento-row.row
        .span5
          %article.post
            %hgroup
              %h2= t('.campaign_funding.alleged_patrimony.title')
            .entry-content
              %p= t('.campaign_funding.alleged_patrimony.body')
            #patrimonies-statistics{ data: { men: @statistics.men_patrimonies, women: @statistics.women_patrimonies } }
            #piechart_patrimonio
        .span5
          %article.post
            %hgroup
              %h2= t('.campaign_funding.campaign_resources.title')
            .entry-content
              %p= t('.campaign_funding.campaign_resources.body')
            #revenues-statistics{ data: { men: @statistics.men_revenues, women: @statistics.women_revenues } }
            #piechart_recursos
  %hr

  .scrollblock
    %section#feature
      .container
        .row
          .span12
            %article
              %p
                = t '.conclusion_html',
                    donamaria: link_to('DonaMaria', '#top')
  %hr

  %section#participe.single-page.scrollblock
    .container.landing
      %article.post
        %h1.folio-headline= t('.hands_on.title')
        %p
          %i.fa.fa-certificate.fa= t('.hands_on.registering')
          %br
          %i.fa.fa-certificate.fa= t('.hands_on.looking_up')
          %br
          %i.fa.fa-certificate.fa= t('.hands_on.contributing')
          %br
          %i.fa.fa-certificate.fa= t('.hands_on.creating')
          %br
          %i.fa.fa-certificate.fa= t('.hands_on.promoting')
          %br
        %p= t('.hands_on.footer')
      .row.text-center
        = form_tag candidates_path, class: 'form-search', method: 'get' do
          = text_field_tag :search, params[:search], placeholder: 'Pesquisar Candidata', class: 'search-query'
          = button_tag type: 'submit', name: nil, class: 'btn' do
            %i.fa.fa-search.fa-lg
      .row
        = link_to 'Listar Candidatas', candidates_path, class: 'legend btn', data: { no_turbolink: true }
  %hr

  %section#quem-somos.single-page.scrollblock
    .container
      .align
        %i.fa.fa-users
      %h1 Quem Somos
      .row
        .span2.offset3
          .teamalign= image_tag 'isadora.jpg', size: '60x60'
          %h3 Isadora
          .job-position Desenvolvedora
        .span2
          .teamalign= image_tag 'embs.jpg', size: '60x60'
          %h3 Matheus
          .job-position Desenvolvedor
        .span2
          .teamalign= image_tag 'yves.jpg', size: '60x60'
          %h3 Yves
          .job-position Desenvolvedor
      .row
        .span10.offset1
          %hr.featurette-divider
          .featurette
            %h2.featurette-heading= t('.thanks.title')
            %p= t('.thanks.to_hackathon_attendees')
            %p= t('.thanks.to_the_house_of_representatives')
            %p= t('.thanks.to_the_researchers')
          %hr.featurette-divider

  %section#hackathon.single-page.scrollblock
    .container
      .align
      %h1= t('.hackathon.title')
      .row
        .span12
          #theme-form.cform
            %p= t('.hackathon.body')
  %hr
  .footer-wrapper
    .container
      %footer
        %small Desenvolvido por BuriTi.