config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  resources :representatives
  resources :candidates, controller: 'representatives', type: 'Candidate'
  resources :ambassadors, controller: 'representatives', type: 'Ambassador'

  resources :proposals do
    resources :comments
    resources :promissories do
      collection { get :preview }
    end
    member do
      put "like", to: "proposals#upvote"
      put "dislike", to: "proposals#downvote"
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
end

app/models/candidate.rb
class Candidate < Representative
  has_many :candidatures, foreign_key: :representative_id
end

app/models/representable/candidate.rb
module Representable
  class Candidate < OpenStruct
  end
end

app/views/candidates/_candidate.html.haml
- candidature = candidate.candidatures.first.decorate
.panel.panel-default
  .panel-heading
    .panel-title
      = candidate.name
  .panel-body
    .col-md-2
      .text-center
        = link_to (image_tag('politica.png',size: '100x100')), candidate_path(candidate.id)
    .col-md-4
      %table.table
        %tr
          %td Profissão
          %td= candidate.occupation
        %tr
          %td Cargo
          %td= candidature.job_title
        %tr
          %td Partido
          %td= candidature.political_party_symbol
        %tr
          %td Coligação
          %td= candidature.political_caption
    .col-md-6
      %table.table
        %thead
          %tr
            %th.text-center Receita
            %th.text-center Despesa
            %th.text-center Patrimônio
        %tr
          %td.text-center
            = link_to number_to_currency(candidature.total_revenue), "#revenue-#{(candidature.id)}", class: 'btn btn-success', data: { toggle: :modal }
          %td.text-center
            = link_to number_to_currency(candidature.total_expenditure), "#expenditure-#{(candidature.id)}", class: 'btn btn-danger', data: { toggle: :modal }
          %td.text-center
            = link_to number_to_currency(candidature.total_patrimony), "#patrimony-#{(candidature.id)}", class: 'btn btn-warning', data: { toggle: :modal }

= render partial: 'shared/modal', locals: { candidature: candidature, model: 'revenue' }
= render partial: 'shared/modal', locals: { candidature: candidature, model: 'expenditure' }
= render partial: 'shared/modal', locals: { candidature: candidature, model: 'patrimony' }

app/views/candidates/_profile.html.haml
- candidature = representative.candidatures.first.decorate
.panel.panel-default
  .panel-heading
    .panel-title
      = representative.name
  .panel-body
    .row
      .col-md-4
        .text-center
          = link_to (image_tag('politica.png',size: '100x100')), representative_path(representative.id)
      .col-md-8
        = representative.presentation
    .row
      .col-md-4
        %table.table
          %tr
            %td Profissão
            %td= representative.occupation
          %tr
            %td Cargo
            %td= candidature.job_title
          %tr
            %td Partido
            %td= candidature.political_party_symbol
          %tr
            %td Coligação
            %td= candidature.political_caption
          %tr
            %td WebPage
            %td= representative.web_page
          %tr
            %td RedesSociais
            %td= representative.social_network
          %tr
            %td Telefone
            %td= representative.phone_number
        .panel.panel-default
          .panel-heading
            .panel-title
              %label
                = 'Propostas:'
                = representative.proposals.count
          .panel-body
            = representative.proposals_titles.html_safe
        .panel.panel-default
          .panel-heading
            .panel-title
              %label
                = 'Financiamento:'
                = number_to_currency(rand(100..10000), precision: 2, unit: "R$", separator: ",")
          .panel-body
        .panel.panel-default
          .panel-heading
            .panel-title
              %label
                = 'Apoiadores:'
                = representative.supporters_count
          .panel-body
            = representative.supporters_id
      .col-md-8
        = render @representative.proposals