config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  resources :representatives
  resources :candidates, controller: 'representatives', type: 'Candidate'
  resources :ambassadors, controller: 'representatives', type: 'Ambassador'

  resources :proposals do
    resources :comments
    resources :promissories do
      collection { get :preview }
    end
    member do
      put "like", to: "proposals#upvote"
      put "dislike", to: "proposals#downvote"
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :representative
  has_many :comments
  has_many :promissories
  has_many :users, through: :promissories

  acts_as_votable
  acts_as_commentable

  validates :representative, presence: true

  scope :recent, -> { order(created_at: :desc).limit(10)}
  scope :pop, -> { Proposal.all.where(id: Proposal.all.map(&:id)).to_a.sort_by(&:score).reverse}

  def self.search(description)
    where("description like ?", "%#{description}%")
  end

  def score
    self.get_upvotes.size - self.get_downvotes.size
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  def index
    if params[:search].present?
      @proposals = Proposal.search(params[:search]).page(params[:page]).per(10)
    else
      @proposals = Proposal.all.page(params[:page]).per(10)
    end
  end

  def new
    @proposal = Proposal.new
  end

  def create
    if user_signed_in?
      @representative = Representative.where(user_id: current_user.id).first
      @proposal = Proposal.new(proposal_params)
      @proposal.representative = @representative
      if @proposal.save
      redirect_to '/proposals'
      flash[:success] = "Proposta cadastrada com sucesso!"
      else
        flash[:error] = @proposal.errors.full_messages_for(@proposal.errors.first.first)
      end
    else
      redirect_to '/users/sign_in'
      flash[:alert] = 'Favor efetuar login'
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def update
    @proposal = Proposal.find(params[:id])
    @proposal.save
  end

  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy
  end

  def upvote
    if user_signed_in?
      @proposal = Proposal.find(params[:id])
      @proposal.upvote_by current_user
      redirect_to proposals_path
    else
      redirect_to '/users/sign_in'
      flash[:alert] = 'Favor efetuar login'
    end
  end

  def downvote
    if user_signed_in?
      @proposal = Proposal.find(params[:id])
      @proposal.downvote_from current_user
      redirect_to proposals_path
    else
      redirect_to '/users/sign_in'
      flash[:alert] = 'Favor efetuar login'
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:title, :description, :representative_id)
  end
end

app/views/proposals/_form.html.haml
= form_for Proposal.new do |p|
  = p.label :Titulo
  = p.text_field :title, placeholder: 'Titulo'
  = p.label :Descrição
  = p.text_area :description, rows: '6', placeholder: 'Descreva sua proposta', class: 'form-control'
  = p.submit 'Concluir', class: 'btn btn-success pull-right'

app/views/proposals/_proposal.html.haml
.row.box-proposal
  .col-md-12
    .col-md-9
      .col-md-12
        %b
          = proposal.title
        %label
          = proposal.description
    .col-md-1.pull-right
      .row
        = link_to '<i class="fa fa-usd"></i>'.html_safe, new_proposal_promissory_path(proposal)
      .row
        %b= number_to_currency(proposal.promissories.sum(:amount), precision: 2, unit: "R$", separator: ",")
    .col-md-1
      .row
        = link_to '<i class="fa fa-comment"></i>'.html_safe, proposal_comments_path(proposal)
      .row
        %b= proposal.comments.count
    .col-md-1
      .row
        = link_to '<i class="fa fa-chevron-up"></i> '.html_safe, like_proposal_path(proposal), method: :put
      .row
        %b= proposal.score
      .row
        = link_to '<i class="fa fa-chevron-down"></i>'.html_safe, dislike_proposal_path(proposal), method: :put
  .col-md-12.comment
    = render proposal.comments
  .col-md-12
    - if user_signed_in?
      = render partial: 'comments/form', locals: { proposal: proposal }
    - else
      %textarea
        = flash[:notice] = 'Faça Login para comentar'

app/views/proposals/index.html.haml
.container
  = render @proposals

app/views/proposals/new.html.haml
.container
  .row.box
    = render 'form'